// <auto-generated />
namespace EducationAdminSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddGradeGradeSort : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGradeGradeSort));
        
        string IMigrationMetadata.Id
        {
            get { return "201411010701078_AddGradeGradeSort"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
